# Generated by Django 5.1.5 on 2025-01-30 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=255, verbose_name="Задача")),
                ("deadline", models.DateField(verbose_name="Срок выполнения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Not Started", "Не начата"),
                            ("In Progress", "В процессе"),
                            ("Completed", "Завершена"),
                        ],
                        default="Not Started",
                        max_length=50,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="users.employee",
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtasks",
                        to="tracker.task",
                        verbose_name="Родительская задача",
                    ),
                ),
            ],
        ),
    ]
